name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.0

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Upload to OSS
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: oss-cn-shanghai.aliyuncs.com
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
      - run: ossutil cp -rf ./.vitepress/dist/ oss://docs-laihaojie-top/

      - name: Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: laihaojie/laihaojie.github.io
          publish_branch: docs
          destination_dir: docs
          publish_dir: ./.vitepress/dist

      - name: Send success message
        if: success()
        run: curl -G "https://wss.laihaojie.com/api/tools/releaseSuccess" --data-urlencode "id=文档"

      - name: Send failed message
        if: failure()
        run: curl -G "https://wss.laihaojie.com/api/tools/releaseFailed" --data-urlencode "id=文档"
